# Generated by Django 3.0.8 on 2020-08-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='body',
            new_name='descriotion',
        ),
    ]
