# Generated by Django 3.0.8 on 2020-08-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20200830_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='descriotion',
            new_name='description',
        ),
    ]
