# Generated by Django 3.2.9 on 2022-04-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20200830_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
    ]
